using EasyBizDBTypes.Common;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.Serialization;
using System.Text;
using System.Threading.Tasks;

namespace EasyBizDBTypes.Masters
{
    [DataContract]
    [Serializable]
    public class BinLevelDetailsTypes : BaseType
    {
        [DataMember]
        public int ID { get; set; }
        [DataMember]
        public string AutoGeneratedCode { get; set; }
        [DataMember]
        public int LevelID { get; set; }
        [DataMember]
        public string LevelName { get; set; }
        [DataMember]
        public string SubLevelCode { get; set; }
        [DataMember]
        public string SubLevelName { get; set; }
        [DataMember]
        public string HeaderCode { get; set; }
        [DataMember]
        public int MaxCapacity { get; set; }
        [DataMember]
        public string BinType { get; set; }
        [DataMember]
        public Boolean DefaultReceivingBin { get; set; }
        [DataMember]
        public Boolean DefaultSalesReceivingBin { get; set; }
        [DataMember]
        public Boolean DefaultSellingBin { get; set; }
        [DataMember]
        public int StoreID { get; set; }
        [DataMember]
        public string StoreCode { get; set; }
        [DataMember]
        public string Purchase { get; set; }
        [DataMember]
        public string BinBarcode { get; set; }
        [DataMember]
        public List<BinLevelDetailsTypes> BinLevelDetailsList { get; set; }
    }
}
