using EasyBizAbsDAL.Masters;
using EasyBizDBTypes.Common;
using EasyBizDBTypes.Masters;
using EasyBizRequest.Masters.BinSubLevelRequest;
using EasyBizResponse.Masters.BinSubLevelResponse;
using MsSqlDAL.Common;
using ResourceStrings;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using EasyBizRequest;
using EasyBizResponse;

namespace MsSqlDAL.Masters
{
    public class BinLevelDetailsDAL : BaseBinLevelDetailsDAL
    {
        SqlConnection _ConnectionObj;
        SqlCommand _CommandObj;
        string _ConnectionString; Enums.RequestFrom _RequestFrom;
        public override BaseResponseType DeleteByIDs(BaseRequestType RequestObj)
        {
            throw new NotImplementedException();
        }

        public override BaseResponseType DeleteRecord(BaseRequestType RequestObj)
        {
            throw new NotImplementedException();
        }

        public override BaseResponseType InsertRecord(BaseRequestType RequestObj)
        {
            var RequestData = (SaveBinLevelRequest)RequestObj;
            var ResponseData = new SaveBinSubLevelResponse();
            var sqlCommon = new MsSqlCommon();
            try
            {
                _ConnectionString = RequestData.ConnectionString;
                _RequestFrom = RequestData.RequestFrom;

                sqlCommon.InitializeDataComponents(ref _ConnectionObj, ref _CommandObj, ref _ConnectionString, ref _RequestFrom);
                _CommandObj = new SqlCommand("InsertOrUpdateBinLevelDetails", _ConnectionObj);
                _CommandObj.CommandType = CommandType.StoredProcedure;

                var BinLevelDetails = _CommandObj.Parameters.Add("@BinLevelDetails", SqlDbType.Xml);
                BinLevelDetails.Direction = ParameterDirection.Input;
                BinLevelDetails.Value = BinConfigDetailsXML(RequestData.BinLevelDetailsList);

                SqlParameter StatusCode = _CommandObj.Parameters.Add("@OpStatusCode", SqlDbType.Int);
                StatusCode.Direction = ParameterDirection.Output;

                SqlParameter StatusMsg = _CommandObj.Parameters.Add("@OpStatusMessage", SqlDbType.NVarChar, 500);
                StatusMsg.Direction = ParameterDirection.Output;

                SqlParameter ID = _CommandObj.Parameters.Add("@ID", SqlDbType.NVarChar, 50);
                ID.Direction = ParameterDirection.Output;

                _CommandObj.CommandType = CommandType.StoredProcedure;
                _CommandObj.ExecuteNonQuery();

                string strStatusCode = StatusCode.Value.ToString();
                if (strStatusCode == "1")
                {
                    ResponseData.DisplayMessage = CommonStrings.SuccessfulSaveMessage.Replace("{}", "Bin Config Details");
                    ResponseData.StatusCode = Enums.OpStatusCode.Success;
                    ResponseData.IDs = ID.Value.ToString();
                }
                else if (strStatusCode == "2")
                {
                    ResponseData.DisplayMessage = CommonStrings.AlreadyExists.Replace("{}", "Bin Config Details");
                }
                else
                {
                    ResponseData.DisplayMessage = Convert.ToString(StatusMsg.Value);
                }
            }
            catch (Exception ex)
            {
                ResponseData.StatusCode = Enums.OpStatusCode.GeneralError;
                ResponseData.DisplayMessage = CommonStrings.SaveErrorMessage.Replace("{}", "Bin Details");
                ResponseData.ExceptionMessage = ex.Message;
                ResponseData.StackTrace = ex.StackTrace;
            }
            finally
            {
                sqlCommon.CloseConnection(_ConnectionObj);
            }

            return ResponseData;
        }

        public string BinConfigDetailsXML(List<BinLevelDetailsTypes> BinConfigDetailsList)
        {
            StringBuilder sSql = new StringBuilder();
            foreach (BinLevelDetailsTypes objBinConfigDetails in BinConfigDetailsList)
            {
                sSql.Append("<BinLevelDetails>");
                sSql.Append("<ID>" + (objBinConfigDetails.ID) + "</ID>");
                sSql.Append("<AutoGeneratedCode>" + (objBinConfigDetails.AutoGeneratedCode) + "</AutoGeneratedCode>");
                sSql.Append("<LevelID>" + (objBinConfigDetails.LevelID) + "</LevelID>");
                sSql.Append("<LevelName>" + (objBinConfigDetails.LevelName) + "</LevelName>");
                sSql.Append("<SubLevelCode>" + (objBinConfigDetails.SubLevelCode) + "</SubLevelCode>");
                sSql.Append("<SubLevelName>" + (objBinConfigDetails.SubLevelName) + "</SubLevelName>");
                sSql.Append("<HeaderCode>" + (objBinConfigDetails.HeaderCode) + "</HeaderCode>");
                sSql.Append("<MaxCapacity>" + (objBinConfigDetails.MaxCapacity) + "</MaxCapacity>");
                sSql.Append("<BinType>" + (objBinConfigDetails.BinType) + "</BinType>");
                sSql.Append("<DefaultReceivingBin>" + (objBinConfigDetails.DefaultReceivingBin) + "</DefaultReceivingBin>");
                sSql.Append("<DefaultSalesReceivingBin>" + (objBinConfigDetails.DefaultSalesReceivingBin) + "</DefaultSalesReceivingBin>");
                sSql.Append("<DefaultSellingBin>" + (objBinConfigDetails.DefaultSellingBin) + "</DefaultSellingBin>");
                sSql.Append("<StoreID>" + (objBinConfigDetails.StoreID) + "</StoreID>");
                sSql.Append("<StoreCode>" + (objBinConfigDetails.StoreCode) + "</StoreCode>");
                sSql.Append("<Active>" + objBinConfigDetails.Active + "</Active>");
                sSql.Append("<CreateBy>" + objBinConfigDetails.CreateBy + "</CreateBy>");
                sSql.Append("<Purchase>" + objBinConfigDetails.Purchase + "</Purchase>");
                sSql.Append("<BinBarcode>" + objBinConfigDetails.BinBarcode + "</BinBarcode>");
                sSql.Append("</BinLevelDetails>");
            }
            return sSql.ToString();
        }

        public override BaseResponseType SelectAll(BaseRequestType RequestObj)
        {
            var BinMasterList = new List<BinLevelDetailsTypes>();
            var RequestData = (SelectAllBinLevelRequest)RequestObj;
            var ResponseData = new SelectAllBinSubLevelResponse();
            SqlDataReader objReader;
            var sqlCommon = new MsSqlCommon();
            try
            {
                _ConnectionString = RequestData.ConnectionString;
                _RequestFrom = RequestData.RequestFrom;

                sqlCommon.InitializeDataComponents(ref _ConnectionObj, ref _CommandObj, ref _ConnectionString, ref _RequestFrom);
                //string sSql = "Select * from AgentMaster with(NoLock) where Active='{0}'";
                string sSql = "Select * from StoreBinConfigDetails Where StoreID = " + RequestData.ID;



                _CommandObj = new SqlCommand(sSql, _ConnectionObj);
                _CommandObj.CommandType = CommandType.Text;
                objReader = _CommandObj.ExecuteReader();
                if (objReader.HasRows)
                {
                    while (objReader.Read())
                    {
                        var objBin = new BinLevelDetailsTypes();
                        objBin.ID = objReader["ID"] != DBNull.Value ? Convert.ToInt32(objReader["ID"]) : 0;
                        objBin.LevelID = objReader["LevelID"] != DBNull.Value ? Convert.ToInt32(objReader["LevelID"]) : 0;
                        objBin.LevelName = Convert.ToString(objReader["LevelName"]);
                        objBin.HeaderCode = Convert.ToString(objReader["HeaderCode"]);
                        objBin.AutoGeneratedCode = Convert.ToString(objReader["AutoGeneratedCode"]);
                        objBin.SubLevelCode = Convert.ToString(objReader["SubLevelCode"]);
                        objBin.SubLevelName = Convert.ToString(objReader["SubLevelName"]);
                        objBin.DefaultReceivingBin = Convert.ToBoolean(objReader["DefaultReceivingBin"]);
                        objBin.BinBarcode = Convert.ToString(objReader["BinBarcode"]);
                        
                        /*objBin.CreateOn = objReader["CreateOn"] != DBNull.Value ? Convert.ToDateTime(objReader["CreateOn"]) : DateTime.Now;
                        objBin.CreateBy = objReader["CreateBy"] != DBNull.Value ? Convert.ToInt32(objReader["CreateBy"]) : 0;
                        objBin.UpdateOn = objReader["UpdateOn"] != DBNull.Value ? Convert.ToDateTime(objReader["UpdateOn"]) : DateTime.Now;
                        objBin.UpdateBy = objReader["UpdateBy"] != DBNull.Value ? Convert.ToInt32(objReader["UpdateBy"]) : 0; ;*/
                        //objAgent.SCN = objReader["SCN"] != DBNull.Value ? Convert.ToInt32(objReader["SCN"]) : 0;
                        objBin.Active = objReader["Active"] != DBNull.Value ? Convert.ToBoolean(objReader["Active"]) : true;
                        BinMasterList.Add(objBin);
                    }
                    ResponseData.StatusCode = Enums.OpStatusCode.Success;
                    ResponseData.BinSubLevelList = BinMasterList;

                    //ResponseData.ResponseDynamicData = AgentList;
                }
                else
                {
                    ResponseData.StatusCode = Enums.OpStatusCode.RecordNotFound;
                    ResponseData.DisplayMessage = CommonStrings.NoRecordFound.Replace("{}", "Bin Details");
                }
            }
            catch (Exception ex)
            {
                ResponseData.StatusCode = Enums.OpStatusCode.RecordNotFound;
                ResponseData.DisplayMessage = ex.Message;
            }
            finally
            {
                sqlCommon.CloseConnection(_ConnectionObj);
            }
            return ResponseData;
        }

        public override BaseResponseType SelectByIDs(BaseRequestType RequestObj)
        {
            var BinMasterList = new List<BinLevelDetailsTypes>();
            var RequestData = (SelectByIDBinLevelRequest)RequestObj;
            var ResponseData = new SelectByIDBinLevelDetailsResponse();
            SqlDataReader objReader;
            var sqlCommon = new MsSqlCommon();
            try
            {
                _ConnectionString = RequestData.ConnectionString;
                _RequestFrom = RequestData.RequestFrom;

                sqlCommon.InitializeDataComponents(ref _ConnectionObj, ref _CommandObj, ref _ConnectionString, ref _RequestFrom);
                //string sSql = "Select * from AgentMaster with(NoLock) where Active='{0}'";
                string sSql = "Select * from StoreBinConfigDetails Where StoreID = " + RequestData.ID +" and LevelID = " + RequestData.LevelID;



                _CommandObj = new SqlCommand(sSql, _ConnectionObj);
                _CommandObj.CommandType = CommandType.Text;
                objReader = _CommandObj.ExecuteReader();
                if (objReader.HasRows)
                {
                    while (objReader.Read())
                    {
                        var objBin = new BinLevelDetailsTypes();
                        objBin.ID = objReader["ID"] != DBNull.Value ? Convert.ToInt32(objReader["ID"]) : 0;
                        objBin.LevelID = objReader["LevelID"] != DBNull.Value ? Convert.ToInt32(objReader["LevelID"]) : 0;
                        objBin.LevelName = Convert.ToString(objReader["LevelName"]);
                        objBin.HeaderCode = Convert.ToString(objReader["HeaderCode"]);
                        objBin.AutoGeneratedCode = Convert.ToString(objReader["AutoGeneratedCode"]);
                        objBin.SubLevelCode = Convert.ToString(objReader["SubLevelCode"]);
                        objBin.SubLevelName = Convert.ToString(objReader["SubLevelName"]);
                        objBin.DefaultReceivingBin = objReader["DefaultReceivingBin"] != DBNull.Value ? Convert.ToBoolean(objReader["DefaultReceivingBin"]) : false;
                        objBin.DefaultSalesReceivingBin = objReader["DefaultSalesReceivingBin"] != DBNull.Value ? Convert.ToBoolean(objReader["DefaultSalesReceivingBin"]) : false;
                        objBin.DefaultSellingBin = objReader["DefaultSellingBin"] != DBNull.Value ? Convert.ToBoolean(objReader["DefaultSellingBin"]) : false;
                        //objAgent.Active = Convert.ToString(objReader["Active"]);
                        /*objBin.CreateOn = objReader["CreateOn"] != DBNull.Value ? Convert.ToDateTime(objReader["CreateOn"]) : DateTime.Now;
                        objBin.CreateBy = objReader["CreateBy"] != DBNull.Value ? Convert.ToInt32(objReader["CreateBy"]) : 0;
                        objBin.UpdateOn = objReader["UpdateOn"] != DBNull.Value ? Convert.ToDateTime(objReader["UpdateOn"]) : DateTime.Now;
                        objBin.UpdateBy = objReader["UpdateBy"] != DBNull.Value ? Convert.ToInt32(objReader["UpdateBy"]) : 0; ;*/
                        //objAgent.SCN = objReader["SCN"] != DBNull.Value ? Convert.ToInt32(objReader["SCN"]) : 0;
                        objBin.Purchase = Convert.ToString(objReader["Purchase"]);
                        objBin.BinBarcode = Convert.ToString(objReader["BinBarcode"]);
                        objBin.Active = objReader["Active"] != DBNull.Value ? Convert.ToBoolean(objReader["Active"]) : true;
                        BinMasterList.Add(objBin);
                    }
                    ResponseData.StatusCode = Enums.OpStatusCode.Success;
                    ResponseData.BinSubLevelList = BinMasterList;

                    //ResponseData.ResponseDynamicData = AgentList;
                }
                else
                {
                    ResponseData.StatusCode = Enums.OpStatusCode.RecordNotFound;
                    ResponseData.DisplayMessage = CommonStrings.NoRecordFound.Replace("{}", "Bin Details");
                }
            }
            catch (Exception ex)
            {
                ResponseData.StatusCode = Enums.OpStatusCode.RecordNotFound;
                ResponseData.DisplayMessage = ex.Message;
            }
            finally
            {
                sqlCommon.CloseConnection(_ConnectionObj);
            }
            return ResponseData;
        }

        public override BaseResponseType SelectRecord(BaseRequestType RequestObj)
        {
            var BinMasterList = new List<BinLevelDetailsTypes>();
            var RequestData = (SelectByIDBinLevelRequest)RequestObj;
            var ResponseData = new SelectByIDBinLevelDetailsResponse();
            SqlDataReader objReader;
            var sqlCommon = new MsSqlCommon();
            try
            {
                _ConnectionString = RequestData.ConnectionString;
                _RequestFrom = RequestData.RequestFrom;

                sqlCommon.InitializeDataComponents(ref _ConnectionObj, ref _CommandObj, ref _ConnectionString, ref _RequestFrom);
                //string sSql = "Select * from AgentMaster with(NoLock) where Active='{0}'";
                string sSql = "Select * from StoreBinConfigDetails Where StoreID = " + RequestData.ID + " and LevelID = " + RequestData.LevelID + " and HeaderCode ='"+RequestData.HeaderCode +"'";



                _CommandObj = new SqlCommand(sSql, _ConnectionObj);
                _CommandObj.CommandType = CommandType.Text;
                objReader = _CommandObj.ExecuteReader();
                if (objReader.HasRows)
                {
                    while (objReader.Read())
                    {
                        var objBin = new BinLevelDetailsTypes();
                        objBin.ID = objReader["ID"] != DBNull.Value ? Convert.ToInt32(objReader["ID"]) : 0;
                        objBin.LevelID = objReader["LevelID"] != DBNull.Value ? Convert.ToInt32(objReader["LevelID"]) : 0;
                        objBin.LevelName = Convert.ToString(objReader["LevelName"]);
                        objBin.HeaderCode = Convert.ToString(objReader["HeaderCode"]);
                        objBin.AutoGeneratedCode = Convert.ToString(objReader["AutoGeneratedCode"]);
                        objBin.SubLevelCode = Convert.ToString(objReader["SubLevelCode"]);
                        objBin.SubLevelName = Convert.ToString(objReader["SubLevelName"]);
                        objBin.MaxCapacity = objReader["MaxCapacity"] != DBNull.Value ? Convert.ToInt32(objReader["MaxCapacity"]) : 0;
                        objBin.BinType = null;
                        objBin.DefaultReceivingBin = objReader["DefaultReceivingBin"] != DBNull.Value ? Convert.ToBoolean(objReader["DefaultReceivingBin"]) : false;
                        objBin.DefaultSalesReceivingBin = objReader["DefaultSalesReceivingBin"] != DBNull.Value ? Convert.ToBoolean(objReader["DefaultSalesReceivingBin"]) : false;
                        objBin.DefaultSellingBin = objReader["DefaultSellingBin"] != DBNull.Value ? Convert.ToBoolean(objReader["DefaultSellingBin"]) : false;
                        objBin.StoreID = objReader["StoreID"] != DBNull.Value ? Convert.ToInt32(objReader["StoreID"]) : 0;
                        objBin.StoreCode = Convert.ToString(objReader["StoreCode"]);
                        objBin.Purchase = Convert.ToString(objReader["Purchase"]);
                        objBin.BinBarcode = Convert.ToString(objReader["BinBarcode"]);
                        objBin.Active = objReader["Active"] != DBNull.Value ? Convert.ToBoolean(objReader["Active"]) : true;
                        BinMasterList.Add(objBin);
                    }
                    ResponseData.StatusCode = Enums.OpStatusCode.Success;
                    ResponseData.BinSubLevelList = BinMasterList;

                    //ResponseData.ResponseDynamicData = AgentList;
                }
                else
                {
                    ResponseData.StatusCode = Enums.OpStatusCode.RecordNotFound;
                    ResponseData.DisplayMessage = CommonStrings.NoRecordFound.Replace("{}", "Bin Details");
                }
            }
            catch (Exception ex)
            {
                ResponseData.StatusCode = Enums.OpStatusCode.RecordNotFound;
                ResponseData.DisplayMessage = ex.Message;
            }
            finally
            {
                sqlCommon.CloseConnection(_ConnectionObj);
            }
            return ResponseData;
        }

        public override BaseResponseType UpdateRecord(BaseRequestType RequestObj)
        {
            throw new NotImplementedException();
        }
    }
}
